name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]
        os: [windows-latest, ubuntu-latest]
        dotnetver: [6.x, 7.x]

    runs-on: ${{matrix.os}}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{matrix.dotnetver}}

    - name: Compile solution
      run: dotnet build -c ${{matrix.configuration}}

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test
      
    - name: Upload artifacts
      uses: actions/upload-artifacts@v3
      with:
        name: artifacts-${{matrix.os}}-${{matrix.configuration}}-${{matrix.dotnetver}}
        path: bin
