name: Windows Installer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]
        os: [windows-latest]
        dotnetver: [6.x]

    runs-on: ${{matrix.os}}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{matrix.dotnetver}}
    - name: Install NSIS
      run: curl -Lo nsis.exe 'https://downloads.sourceforge.net/project/nsis/NSIS%203/3.08/nsis-3.08-setup.exe?ts=gAAAAABkTqhlt8_k2YSnrRRbuddedOSdvuH5h6n-rbc_dmcD23ABrtLFQXEIRRptACed_rW6zgWtrzRzSQaeMImViXISO2Y22A%3D%3D&r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fnsis%2Ffiles%2FNSIS%25203%2F3.08%2Fnsis-3.08-setup.exe%2Fdownload' && ./nsis.exe /S

    - name: Compile solution
      run: dotnet build -c ${{matrix.configuration}}

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test
      
    - name: Download GTK dlls
      run: curl -LO https://raw.githubusercontent.com/GtkSharp/Dependencies/master/gtk-3.24.24.zip && mkdir gtk && unzip gtk-3.24.24.zip -d gtk

    - name: Build Installer
      run: makensis installer.nsis

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifacts-windows-installer
        path: mediatek-installer.exe
